sudo: required # required by Docker

language: node_js
node_js:
  - 10.19.0
cache: npm

services:
  - docker

script:
  - npm audit
  - npm run lint
  - npm test

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin # add AWS in PATH
  - eval $(aws ecr get-login --no-include-email --region $AWS_REGION)
  - docker build -t giftcodeserver:$TRAVIS_COMMIT .
  - export DOCKER_REGISTRY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  - docker tag giftcodeserver:$TRAVIS_COMMIT $DOCKER_REGISTRY_URI/giftcodeserver:$TRAVIS_COMMIT
  - docker push $DOCKER_REGISTRY_URI/giftcodeserver:$TRAVIS_COMMIT
